version: '3.8'

services:
  vban:
    image: ghcr.io/stefan-ffr/vban-streamer-docker:latest
    privileged: true
    network_mode: host
    environment:
      - VBAN_TARGET_IP=192.168.1.100  # Adjust as needed
      - BT_DEVICE_NAME=VBAN-Speaker
    volumes:
      - /var/run/dbus:/var/run/dbus
    restart: unless-stopped
